
export const POPUP_OPEN = 'POPUP_OPEN';

export const POPUP_RESET = 'POPUP_RESET';

export const LOADER_OPEN = 'LOADER_OPEN';

export const LOADER_CLOSE = 'LOADER_CLOSE';

export const ADD_BOOK_SUCESS = 'ADD_BOOK_SUCESS';

export const ADD_BOOK_FAIL = 'ADD_BOOK_FAIL'; 

export const GET_BOOK_SUCESS = 'GET_BOOK_SUCESS';

export const GET_BOOK_FAIL = 'GET_BOOK_FAIL'; 

export const GET_ALL_ITEMS_SUCCESS = 'GET_ALL_ITEMS_SUCCESS';

export const GET_ALL_ITEMS_FAILIURE = 'GET_ALL_ITEMS_FAILIURE';
